global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'accessiq'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['accessiq-app:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: accessiq-app:8081

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']